### ISSUE TITLE
Plasma lens with Wakefields = True

### ISSUE THREAD

**Issue by zhangli28** [AngelFP/Wake-T#135]
Dear All,

I am looking for a clarification for "ActivePlasmaLens" module.
If I want the plasma lens to include "Wakefields = True"  then how "ActivePlasmaLens" parameters should be described.

For example, if I use

drift_1 = Drift(length=0.1)    # bunch enter in the APL after drifting for 10 cm in vacuum
drift_2 = Drift(length=0.3)  # bunch focusing is detected at 30 cm after coming out of APL

apl = ActivePlasmaLens(length=0.2, for_strength=400, wakefields=True, density=1.0e23, wakefield_model='quasi static_2d')

**beamline = Beamline([drift_1, apl, drift_2])**

**now my question is 5 more parameters are required as positional arguments in "apl". How I should define them in "apl" ?**

should I do: 

xi_min=10e-2,        # entrance of apl
xi_max=30.0e-2,   # exit of apl
r_max=500.0e-6,  # radial extent
r_min=-500e-6,    # radial extent

**and could you suggest the criteria of choosing values for n_r and n_xi.**

Thank you.

**Comment by AngelFP** [comment]
Hi @zhangli28,

[Here](https://wake-t.readthedocs.io/en/latest/api/fields/_autosummary/wake_t.physics_models.plasma_wakefields.Quasistatic2DWakefield.html) you can find the list of all possible parameters that can be passed to the `ActivePlasmaLens` when using the `'quasistatic_2d'` wakefield model. In addition to the density, there are, as you say, 5 parameters that must be given. These are `r_max`, `xi_min`, `xi_max`, `n_r` and `n_xi`. The other parameters are optional and depend on your specific case.

Here is an example of how you would use them:
```python

apl = ActivePlasmaLens(
    length=2e-2,
    foc_strength=400,
    wakefields=False,
    density=1.0e23,
    n_out=5,
    r_max=500.0e-6,
    xi_min=-50e-6,
    xi_max=50.0e-6,
    n_r=500,
    n_xi=100,
)
```

Take into account that `xi` is the longitudinal coordinate in the speed-of-light frame (that is, xi = z - ct). Therefore, the beam is basically frozen in this reference frame, and you need to choose `xi_min` and `xi_max` such that the whole beam fits in the simulation window (`xi_min` defines the left boundary and `xi_max` defines the right boundary). In the example above, you have 2 cm APL that you simulate using a moving window with a length of 100 µm that is centered at xi=0 (which I assume is the central position of your particle distribution).

You do not need to give an `r_min`. The geometry of the wakefield model assumes cylindrical symmetry.

With regards to `n_r` and `n_xi`, it depends on your case. You should chose a value that makes sure you can resolve the smallest features of interest in your problem. In an APL, this will typically be the plasma skin depth and the bunch size. A good starting point is having at least 20 grid points per plasma skin depth and at least a few (e.g., 5) grid points per bunch sigma (both in r and xi).

**Comment by zhangli28** [comment]
Hi @AngelFP ,

Thank you for the detailed explanation. It is really helpful. 

Thank you.
