### ISSUE TITLE
PICMI support

### ISSUE THREAD

**Issue by berceanu** [AngelFP/Wake-T#137]
Does it make sense to transition the `Wake-T` input to the PICMI standard?

**Comment by AngelFP** [comment]
Hi @berceanu,
this a possibility we have discussed internally a couple of times, but we currently have no plans to do so (nor resources to implement and maintain a second interface). In principle, I think there's a fraction of the Wake-T API that could be exposed via PICMI. This would be for simulations that involve only a `PlasmaStage`. I'm not sure simulations with a multi-element beamline can be set up PICMI as it is now. Something like https://github.com/ax3l/pydantic-mad could be an option in the future.

**Comment by berceanu** [comment]
I see, so the main problem seems to be that currently the PICMI standard has no provision for beamline elements like quadrupole magnets and so on, right? Thanks for pointing to pydantic-mad, seems like an interesting project, but separate from PICMI, no?

**Comment by AngelFP** [comment]
Yes, I believe that these beamline elements are not possible in PICMI (at least right now). I'm not familiar with the plans for pydantic-mad @ax3l
