### ISSUE TITLE
general question 

### ISSUE THREAD

**Issue by zhangli28** [AngelFP/Wake-T#144]
Dear @AngelFP,

Is it possible to simulate an electron beam crossing the wakefield propagating perpendicular to its direction, i.e., wakefield is propagating along "z" direction and electron beam is propagating along "r" direction ?

I want to use an electron beam to probe the wakefield and track this electron beam interacting with the wakefield. Do you think it can be done with wake-T ?

Thank you.

Best regards,
Zhang

**Comment by AngelFP** [comment]
Hi @zhangli28, sorry for the delay. I was out of office the last days.

In Wake-T, the particle beams move in 3D, but that plasma wakefield is calculated assuming cylindrical symmetry. This means that indeed you can have a beam coming from the side, perpendicular to the wake, but its impact on the wake won't be captured correctly. So, in general, it is not a case that can be well simulated with Wake-T unless the beam charge is so small that it does not have an impact on the wake.

**Comment by zhangli28** [comment]
Hi @AngelFP, thank you for your reply explaination.
