### ISSUE TITLE
Simulation of beam transportation line 

### ISSUE THREAD

**Issue by zhangli28** [AngelFP/Wake-T#146]
Hi @AngelFP ,

can we use Wake-T to simulate electron beam transportation through quadrupole, chicane etc. ?

Thank you.

**Comment by n01r** [comment]
Hi @zhangli28, 

Just chiming in here before @AngelFP may give a more extensive answer:
Here is a list of currently implemented beamline elements https://wake-t.readthedocs.io/en/latest/api/beamline_elements/index.html. Quadrupoles are among them. :+1: Chicanes currently do not seem to be implemented.

Here is an example on some transport involving drifts and an active plasma lens (APL).
https://wake-t.readthedocs.io/en/latest/tutorials/02_plasma_beamline_simulation.html

**Comment by zhangli28** [comment]
@n01r , thanks for answering. Now, my search for beam transportation ends at impactX code. I decide to learn and use impactX for my beamline study.

**Comment by AngelFP** [comment]
Hi @zhangli28,
As @n01r says, you can simulate the beam transport with Wake-T (and chicanes too, as it is just a series of dipoles and drifts). That said, if your simulation does not involve any plasma element, my recommendation would be to use a dedicated code like ImpactX or Ocelot, which are more complete for this type of simulation.
